# Generated by Django 4.1.6 on 2023-02-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_department_contact_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="photo",
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to="contacts/contact/photo"),
        ),
    ]
