from faker import Faker
from apps.animals.models import Animal


def generate_animal(amount: int = 10, is_mark_as_autogenerated=False):
    for _ in range(amount):
        yield Animal(
            name=Faker().first_name(),
            age=Faker().random_int(min=1, max=100),
            is_auto_generated=is_mark_as_autogenerated,
        )
