from django.core.management.base import BaseCommand
from apps.contacts.models import Contact
from logging import getLogger
from apps.contacts.services.generate_contacts import generate_contact


class Command(BaseCommand):
    def add_arguments(self, parser):
        parser.add_argument(
            "--amount",
            help="How many contacts do you want to generate ?",
            type=int,
            default=10,
        )

    def handle(self, *args, **options):
        amount: int = options["amount"]
        logger = getLogger("django")
        queryset = Contact.objects.all()
        logger.info(f"Current amount of contacts -before- {queryset.count()}")

        for contact in generate_contact(amount=amount, is_mark_as_autogenerated=True):
            contact.save()

        logger.info(f"Current amount of contacts -after- {queryset.count()}")

        print()
