# Generated by Django 4.1.7 on 2023-03-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to="users/user/profile_photo"),
        ),
    ]
